// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mib-landing/LandingPreview.tsx": () => import("../components/mockups/mib-landing/LandingPreview.tsx"),
  "./components/mockups/mib-logo/LogoPreview.tsx": () => import("../components/mockups/mib-logo/LogoPreview.tsx")
};
